# Generated by Django 3.1.1 on 2020-10-02 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cameralist',
            fields=[
                ('cameraid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('camerabrand', models.CharField(blank=True, max_length=20, null=True)),
                ('cameraspec', models.CharField(blank=True, max_length=40, null=True)),
                ('inorout', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cameralist',
            },
        ),
        migrations.CreateModel(
            name='Parkinglotlist',
            fields=[
                ('parkinglotid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('parkinglotname', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'parkinglotlist',
            },
        ),
        migrations.CreateModel(
            name='Stafflist',
            fields=[
                ('staffid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('stafffullname', models.CharField(blank=True, max_length=30, null=True)),
                ('parkinglotid', models.ForeignKey(blank=True, db_column='parkinglotid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parkinglotmanager.parkinglotlist')),
            ],
            options={
                'db_table': 'stafflist',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('parkingid', models.AutoField(primary_key=True, serialize=False)),
                ('rfid', models.CharField(blank=True, max_length=12, null=True)),
                ('platenumber', models.CharField(blank=True, max_length=15, null=True)),
                ('plateimgurl', models.CharField(blank=True, max_length=255, null=True)),
                ('inorout', models.BooleanField(blank=True, null=True)),
                ('checktime', models.DateTimeField(blank=True, null=True)),
                ('cameraid', models.ForeignKey(blank=True, db_column='cameraid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parkinglotmanager.cameralist')),
                ('parkinglotid', models.ForeignKey(blank=True, db_column='parkinglotid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parkinglotmanager.parkinglotlist')),
                ('staffid', models.ForeignKey(blank=True, db_column='staffid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parkinglotmanager.stafflist')),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.AddField(
            model_name='cameralist',
            name='parkinglotid',
            field=models.ForeignKey(blank=True, db_column='parkinglotid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parkinglotmanager.parkinglotlist'),
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('rfid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('platenumber', models.CharField(blank=True, max_length=15, null=True)),
                ('plateimgurl', models.CharField(blank=True, max_length=255, null=True)),
                ('checkintime', models.DateTimeField(blank=True, null=True)),
                ('parkinglotid', models.ForeignKey(db_column='parkinglotid', on_delete=django.db.models.deletion.DO_NOTHING, to='parkinglotmanager.parkinglotlist')),
            ],
            options={
                'db_table': 'parking',
                'unique_together': {('rfid', 'parkinglotid')},
            },
        ),
    ]
