# Generated by Django 3.1.1 on 2020-09-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20200919_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('publisher', models.TextField()),
                ('content', models.CharField(max_length=20)),
                ('quanity', models.DecimalField(decimal_places=0, max_digits=100)),
                ('stock', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Game List',
                'verbose_name_plural': 'Game Lists',
                'db_table': 'Game List',
            },
        ),
    ]
