# Generated by Django 3.1.1 on 2020-09-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('platform', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'CPU',
                'verbose_name_plural': 'CPU',
                'db_table': 'CPU',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='shoes_brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='x86',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('memory', models.DecimalField(decimal_places=0, max_digits=4)),
                ('description', models.TextField()),
                ('quanity', models.DecimalField(decimal_places=0, max_digits=4)),
                ('status', models.BooleanField(default=False)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.cpu')),
            ],
            options={
                'verbose_name': 'x86',
                'verbose_name_plural': 'x86',
                'db_table': 'x86',
            },
        ),
        migrations.CreateModel(
            name='shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('foot_size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quanity', models.DecimalField(decimal_places=0, max_digits=3)),
                ('available', models.BooleanField(default=False)),
                ('brand', models.ManyToManyField(to='orm.shoes_brand')),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(max_length=10)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.language')),
            ],
            options={
                'verbose_name': 'Framework',
                'verbose_name_plural': 'Frameworks',
                'db_table': 'Framework',
            },
        ),
        migrations.CreateModel(
            name='arm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('memory', models.DecimalField(decimal_places=0, max_digits=4)),
                ('description', models.TextField()),
                ('quanity', models.DecimalField(decimal_places=0, max_digits=4)),
                ('status', models.BooleanField(default=False)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.cpu')),
            ],
            options={
                'verbose_name': 'arm',
                'verbose_name_plural': 'arm',
                'db_table': 'arm',
            },
        ),
    ]
