# Generated by Django 3.1.1 on 2020-09-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_auto_20200928_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.ManyToManyField(related_name='Shoes_Brand', to='orm.Shoes_Brand'),
        ),
    ]
